steps:
- name: 'us.gcr.io/helix-global/cloud-builders/gradle:openjdk11'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export buildVersion=`cat concourse_build_version`
    export helixRepoUser=${_REPO_USER}
    export helixRepoPassword=${_REPO_PASSWORD}
    gradle publish -PhelixRepoUser=$$helixRepoUser -PhelixRepoPassword=$$helixRepoPassword -PbuildVersion=$$buildVersion
   